global using BlepItLibrary.DataAccess.DTClasses;
global using BlepItLibrary.DataAccess.Interfaces;
global using BlepItLibrary.Enums;
global using BlepItLibrary.Models;
global using Microsoft.Extensions.Caching.Memory;
global using MongoDB.Bson;
global using MongoDB.Bson.Serialization.Attributes;
global using MongoDB.Driver;
global using System.Net.Sockets;
